import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CurrentRouteContextProvider } from "./hooks/CurrentRoute";
import { SelectedDashboardProvider } from "./hooks/SelectedDashboardContext";
import NavBar from "./navBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next UI Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CurrentRouteContextProvider >
          <SelectedDashboardProvider>
            <header className="p-1 pl-4">
              <NavBar />
            </header>
            <main role="main" className="p-4 pt-0.5">
              {children}
            </main>
          </SelectedDashboardProvider>
        </CurrentRouteContextProvider>
      </body>
    </html>
  );
}