import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CurrentRouteContextProvider } from "./hooks/CurrentRoute";
import { SelectedDashboardProvider } from "./hooks/SelectedDashboardContext";
import TopNavBar from "./components/NavBars/TopNavBar";
import { ThemeProvider } from "./hooks/ThemeContext";
import ThemeWrapper from "./components/Wrappers/ThemeWrapper";
import { UserProvider } from "./hooks/UserContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Next UI Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ThemeWrapper>
            <CurrentRouteContextProvider >
              <SelectedDashboardProvider>
                <UserProvider>
                  <header className="p-1">
                    <TopNavBar />
                  </header>
                  <main role="main" className="p-1 pt-0.5">
                    {children}
                  </main>
                </UserProvider>
              </SelectedDashboardProvider>
            </CurrentRouteContextProvider>
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}