import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next UI Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="p-1 pl-4 text-left text-indigo-800 text-lg font-extrabold">
          <nav>
            <Link href="./" className="hover:underline">Home</Link>
          </nav>
        </header>

        <main role="main" className="p-4 pt-0.5">
          {children}
        </main>
      </body>
    </html>
  );
}